language: elixir

dist: trusty
sudo: required

otp_release: 19.3
elixir:
  - 1.6.4
  - 1.5.3
  - 1.4.5

env:
  matrix:
    - CASSANDRA_VERSION=3.9
    - CASSANDRA_VERSION=3.9 AUTHENTICATION=true
    - CASSANDRA_VERSION=2.2.8
    - CASSANDRA_VERSION=2.2.8 AUTHENTICATION=true

matrix:
  include:
    - otp_release: 20.3
      elixir: 1.6.4
      env: CASSANDRA_VERSION=3.9
    - otp_release: 18.3
      elixir: 1.4.5
      env: CASSANDRA_VERSION=3.9

jobs:
  include:
    - stage: format
      before_install: skip
      script: mix format --check-formatted
    - stage: test
      script: mix test

stages:
  - test
  - format

# These steps are taken from: http://cassandra.apache.org/doc/latest/getting_started/installing.html#installation-from-binary-tarball-files.
before_install:
  - java -version
  - wget https://archive.apache.org/dist/cassandra/$CASSANDRA_VERSION/apache-cassandra-$CASSANDRA_VERSION-bin.tar.gz
  - tar -xzf apache-cassandra-$CASSANDRA_VERSION-bin.tar.gz
  - |-
    if [ $AUTHENTICATION = true ]; then
      sed -i -e "s/\(authenticator: \)AllowAllAuthenticator/\1PasswordAuthenticator/" apache-cassandra-$CASSANDRA_VERSION/conf/cassandra.yaml
    fi
  - sh apache-cassandra-$CASSANDRA_VERSION/bin/cassandra
  - for try in {1..12}; do (nodetool version > /dev/null 2>&1 && break) || sleep 5; done
